# Dockerfile.nginx
FROM nginx:alpine

COPY --from=builder /app/.next /usr/share/nginx/html
COPY --from=builder /app/public /usr/share/nginx/html/_next/static/images

COPY nginx.conf /etc/nginx/conf.d/default.conf