version: "3.7"
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    expose:
      - '3000'
    ports:
      - '3000:3000'
    volumes:
      - ./src/:/home/node/app/src
    environment:
    - "VIRTUAL_HOST=hommet.ch"
