server {
  server_name n0k.fr;

  location / {
    root .next;
    index index.html index.htm;
    try_files $uri $uri/ /index.html;
  }

  location /_next/static/ {
    root .next/static;
  }
}